//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timeplan.BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnsattMøteTid
    {
        public int Id { get; set; }
        public System.TimeSpan Start { get; set; }
        public System.TimeSpan Slutt { get; set; }
        public int fk_DagTypeId { get; set; }
        public int fk_AnsattId { get; set; }
    
        public virtual Ansatt Ansatt { get; set; }
        public virtual DagType DagType { get; set; }
    }
}
