//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timeplan.BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BemanningsNorm
    {
        public BemanningsNorm()
        {
            this.Elevs = new HashSet<Elev>();
            this.Elevs1 = new HashSet<Elev>();
        }
    
        public int Id { get; set; }
        public string Navn { get; set; }
        public decimal Antall { get; set; }
    
        public virtual ICollection<Elev> Elevs { get; set; }
        public virtual ICollection<Elev> Elevs1 { get; set; }
    }
}
