//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timeplan.BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DagType
    {
        public DagType()
        {
            this.AnsattMøteTid = new HashSet<AnsattMøteTid>();
            this.StillingsTypeMøteTid = new HashSet<StillingsTypeMøteTid>();
            this.TidsAngivelses = new HashSet<TidsAngivelse>();
        }
    
        public int Id { get; set; }
        public string Navn { get; set; }
    
        public virtual ICollection<AnsattMøteTid> AnsattMøteTid { get; set; }
        public virtual ICollection<StillingsTypeMøteTid> StillingsTypeMøteTid { get; set; }
        public virtual ICollection<TidsAngivelse> TidsAngivelses { get; set; }
    }
}
