//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timeplan.BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElevTilstede
    {
        public int Id { get; set; }
        public Nullable<System.TimeSpan> MandagStart { get; set; }
        public Nullable<System.TimeSpan> MandagSlutt { get; set; }
        public Nullable<System.TimeSpan> TirsdagStart { get; set; }
        public Nullable<System.TimeSpan> TirsdagSlutt { get; set; }
        public Nullable<System.TimeSpan> OnsdagStart { get; set; }
        public Nullable<System.TimeSpan> OnsdagSlutt { get; set; }
        public Nullable<System.TimeSpan> TorsdagStart { get; set; }
        public Nullable<System.TimeSpan> TorsdagSlutt { get; set; }
        public Nullable<System.TimeSpan> FredagStart { get; set; }
        public Nullable<System.TimeSpan> FredagSlutt { get; set; }
        public int fk_ElevId { get; set; }
        public int fk_UkeTypeId { get; set; }
    
        public virtual Elev Elev { get; set; }
        public virtual UkeType UkeType { get; set; }
    }
}
