//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timeplan.BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elev
    {
        public Elev()
        {
            this.ElevTilstedes = new HashSet<ElevTilstede>();
        }
    
        public int Id { get; set; }
        public string Navn { get; set; }
        public decimal SfoProsent { get; set; }
        public string TlfNr { get; set; }
        public int fk_KlasseId { get; set; }
        public Nullable<int> fk_SfoId { get; set; }
        public int fk_SkoleBemanningsNormId { get; set; }
        public Nullable<int> fk_SfoBemanningsNormId { get; set; }
        public int fk_TrinnId { get; set; }
        public int fk_HovedPedagogAnsattId { get; set; }
    
        public virtual Ansatt Ansatt { get; set; }
        public virtual BemanningsNorm BemanningsNorm { get; set; }
        public virtual BemanningsNorm BemanningsNorm1 { get; set; }
        public virtual Klasse Klasse { get; set; }
        public virtual Sfo Sfo { get; set; }
        public virtual Trinn Trinn { get; set; }
        public virtual ICollection<ElevTilstede> ElevTilstedes { get; set; }
    }
}
