//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timeplan.BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skole
    {
        public int Id { get; set; }
        public string Navn { get; set; }
        public int fk_TidsInndelingId { get; set; }
    
        public virtual TidsInndeling TidsInndeling { get; set; }
    }
}
