//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timeplan.BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StillingsType
    {
        public StillingsType()
        {
            this.Ansatts = new HashSet<Ansatt>();
            this.StillingsTypeMøteTid = new HashSet<StillingsTypeMøteTid>();
        }
    
        public int Id { get; set; }
        public string Navn { get; set; }
        public decimal TimerElevarbeid { get; set; }
        public decimal TimerSamarbeid { get; set; }
    
        public virtual ICollection<Ansatt> Ansatts { get; set; }
        public virtual ICollection<StillingsTypeMøteTid> StillingsTypeMøteTid { get; set; }
    }
}
