//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timeplan.BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TidsInndeling
    {
        public TidsInndeling()
        {
            this.Sfoes = new HashSet<Sfo>();
            this.Sfoes1 = new HashSet<Sfo>();
            this.Sfoes2 = new HashSet<Sfo>();
            this.Skoles = new HashSet<Skole>();
        }
    
        public int Id { get; set; }
        public string Navn { get; set; }
        public System.TimeSpan StartTid { get; set; }
        public System.TimeSpan SluttTid { get; set; }
        public System.TimeSpan TidsIntervall { get; set; }
    
        public virtual ICollection<Sfo> Sfoes { get; set; }
        public virtual ICollection<Sfo> Sfoes1 { get; set; }
        public virtual ICollection<Sfo> Sfoes2 { get; set; }
        public virtual ICollection<Skole> Skoles { get; set; }
    }
}
