//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timeplan.BL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TimeplanEntities : DbContext
    {
        public TimeplanEntities()
            : base("name=TimeplanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Ansatt> Ansatts { get; set; }
        public virtual DbSet<AnsattMøteTid> AnsattMøteTid { get; set; }
        public virtual DbSet<AnsattTilstede> AnsattTilstedes { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Avdeling> Avdelings { get; set; }
        public virtual DbSet<BemanningsNorm> BemanningsNorms { get; set; }
        public virtual DbSet<DagType> DagTypes { get; set; }
        public virtual DbSet<Elev> Elevs { get; set; }
        public virtual DbSet<ElevTilstede> ElevTilstedes { get; set; }
        public virtual DbSet<Klasse> Klasses { get; set; }
        public virtual DbSet<Sfo> Sfoes { get; set; }
        public virtual DbSet<Skole> Skoles { get; set; }
        public virtual DbSet<StillingsType> StillingsTypes { get; set; }
        public virtual DbSet<StillingsTypeMøteTid> StillingsTypeMøteTid { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TidsAngivelse> TidsAngivelses { get; set; }
        public virtual DbSet<TidsInndeling> TidsInndelings { get; set; }
        public virtual DbSet<Trinn> Trinns { get; set; }
        public virtual DbSet<UkeType> UkeTypes { get; set; }
    }
}
