//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timeplan.BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UkeType
    {
        public UkeType()
        {
            this.AnsattTilstedes = new HashSet<AnsattTilstede>();
            this.ElevTilstedes = new HashSet<ElevTilstede>();
        }
    
        public int Id { get; set; }
        public string Navn { get; set; }
    
        public virtual ICollection<AnsattTilstede> AnsattTilstedes { get; set; }
        public virtual ICollection<ElevTilstede> ElevTilstedes { get; set; }
    }
}
